stages:
  main:
    cmd: >-
      python3 src/train.py
      --no-cuda
      --dry-run
      --log-interval 10
      --save-model
    deps:
      - src/train.py
    params:
      - train.batch_size
      - train.test_batch_size
      - train.epochs
      - train.lr
      - train.gamma
      - train.seed
    outs:
      - {{cookiecutter.dvc_store}}/models/model.pt